version: '3'

services:
  postgres:
    image: postgres:12
    container_name: postgres
    restart: always
    tty: true
    ports:
      - "5432:5432"
    volumes:
      - ./.docker/init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
      - ./.docker/sql:/tmp/
      - cities-dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: cities
      POSTGRES_PASSWORD: cities
      POSTGRES_DB: cities
volumes:
  cities-dbdata:
    external: true